name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.ACCESS_TOKEN}}

    - name: 'Build and push image'
      run: |
        docker build . --tag ghcr.io/kh4st3h/setarify-frontend:$(date +%s) --tag ghcr.io/kh4st3h/setarify-frontend:latest
        docker push ghcr.io/kh4st3h/setarify-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Update docker compose
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: ${{ secrets.SCRIPT_PATH }}
